### ISSUE TITLE
mscc crashes when tuned outside of amateur bands

### ISSUE THREAD

**Issue by iamtheogre** [w4mmp/Solidus#13]
When tuning outside of the assigned amateur bands mscc switches to the GEN band and then can crash when moving in that band.
Another symptom - mscc was on 17m and when tuning down outside of that band it went to 20m and back to 17m then to 20m etc...
Attaching logs grabbed after that crash.
[17m-20_crash.tar.gz](https://github.com/w4mmp/Solidus/files/5616672/17m-20_crash.tar.gz)

**Comment by w4mmp** [comment]
I think this has been fixed in the latest release on the forum.  Please download and install again.

**Comment by iamtheogre** [comment]
Installed the newest MSCC.
Still crashing when going outside of the amateur band.
E.G. on 20m and tuning down outside of the band it moves to 9MHZ then crashes as you move down more.

**Comment by w4mmp** [comment]
Yep, got it.   What is your tuning step set to?

**Comment by iamtheogre** [comment]
I believe that it was set to1K as that is what I normally use for moving through the band.

**Comment by w4mmp** [comment]
This has been fixed.   Note:  When in an amateur band tuning stops at the top or bottom of the band.
